@startuml
skinparam componentStyle uml

footer
Weather Information Components Diagram by Matthias Bisping
end footer

title Weather Information Components

frame "Backend" {
package "Controller" {
    component ServerStatusController
    component WeatherController
    component WeaterUpdaterController
}

package "Updater" {
    component WeatherUpdateRepository
    [WeatherUpdaterJob]
    component WeatherUpdaterService
}

package "Provider" {
    component OpenWeatherProvider

    note left of OpenWeatherProvider
        Make call to openweathermap.org
        and deserialize the result.
    end note
}

WeatherController --> OpenWeatherProvider
WeatherUpdateRepository --> WeaterUpdaterController
WeatherUpdaterService ..> WeatherUpdaterJob : create new job
WeatherUpdaterJob -> OpenWeatherProvider
WeatherUpdaterJob -> WeatherUpdateRepository : Update

Shell - WeatherUpdaterService : Update city and interval
}

Internet . ServerStatusController
Internet . WeatherController
Internet . WeaterUpdaterController

frame "Frontend" {
    package "Service" {
        [rest-api]
        [websocket]
    }
    package "Componentes" {
        [ServerStatusComponent]
        [ManualComponent]
        [AutomaticComponent]
        [UpdateComponent]
    }
}

[ServerStatusComponent] --> [rest-api]
[ManualComponent] --> [rest-api]
[AutomaticComponent] --> [rest-api]

[UpdateComponent] --> [websocket] : subscribe
[websocket] --> [UpdateComponent] : update

[rest-api] . Internet
Internet . [websocket]

@enduml